export const HEADERS = [
  "Registration Status",
  "Payment Status",
  "Registration Date",
  "Approval Status",
  "Organization Name",
  "Program Name",
  "Provisioned",
  "Assigned Membership/Student ID",
  "Participant First Name",
  "Participant Last Name",
  "Participant Age",
  "Participant Birth date",
  "Participant Gender",
  "Participant Home Phone",
  "Grade",
  "School Name",
  "School Type",
  "Home Address",
  "Home Address City",
  "Home Address State",
  "Home Address Zipcode",
  "Parent Custodial?",
  "Parent First Name",
  "Parent Last Name",
  "Parent Relationship",
  "Parent Mobile Phone",
  "Parent E-mail",
  "Parent Home Phone",
  "Parent Employer",
  "Parent Work Phone",
  "Parent Primary Address",
  "Parent Primary Address City",
  "Parent Primary Address State",
  "Parent Primary Address Zipcode",
  "Second Parent First Name",
  "Second Parent Last Name",
  "Second Parent Relationship",
  "Second Parent Mobile Phone",
  "Second Parent E-mail",
  "Second Parent Home Phone",
  "Second Parent Employer",
  "Second Parent Work Phone",
  "Second Parent Primary Address",
  "Second Parent Primary Address City",
  "Second Parent Primary Address State",
  "Second Parent Primary Address Zipcode",
  "Emer. First Name",
  "Emer. Last Name",
  "Emer. Mobile Phone",
  "Emer. Email",
  "Emer. Home Phone",
  "Emer. May Pick-up",
  "Emer. Relationship",
  "Second Emer. First Name",
  "Second Emer. Last Name",
  "Second Emer. Mobile Phone",
  "Second Emer. Email",
  "Second Emer. Home Phone",
  "Second Emer. May Pick-up",
  "Second Emer. Relationship",
  "Third Emer. First Name",
  "Third Emer. Last Name",
  "Third Emer. Mobile Phone",
  "Third Emer. Email",
  "Third Emer. Home Phone",
  "Third Emer. May Pick-up",
  "Third Emer. Relationship",
  "Primary Care First Name",
  "Primary Care Last Name",
  "Primary Care Work Phone",
  "Carrier",
  "Group Number",
  "Subscriber Name",
  "Diagnosis",
  "Dosage And Time Instructions",
  "Medication Name",
  "Physician",
  "Diagnosed Allergies",
  "Allergies - Other",
  "Epi-pen",
  "Life-Threatening Allergies",
  "Asthma",
  "Dietary",
  "Chronic Medical Conditions",
  "Other",
  "Physical Limitations",
  "Special Requests - Other",
  "Account ID",
  "Account E-mail",
  "Account Number",
  "Registration Number",
  "Participant Number",
  "Legacy Participant Number",
  "Sections",
  "Sections codes",
  "Sections prices",
  "Sections locations",
  "Sections meeting times",
  "Itemized Prices",
  "Full 7-Week Camp: Extended Hours",
  "6-Week Camp: Week options",
  "6-Week Camp: Extended Hours",
  "5-Week Camp: Week options",
  "5-Week Camp: Extended Hours",
  "4-Week Camp: Week options",
  "4-Week Camp: Extended Hours",
  "3-Week Camp: Week options",
  "3-Week Camp: Extended Hours",
  "2-Week Camp: Week options",
  "2-Week Camp: Extended Hours",
  "Non-refundable Registration Fee",
  "Permission to Participate: Text",
  "Permission to Participate: Sign Off",
  "Cancellation & Refund Agreement: Text",
  "Cancellation & Refund Agreement: Sign Off",
  "Summer Recreation Program Objectives/ Behavior Guidelines: Text",
  "Summer Recreation Program Objectives/ Behavior Guidelines: Sign Off",
  "Health History: Text",
  "Health History: Sign Off",
  "Maritime Waterfront Swimming Program Authorization Release for ages 5-14: Text",
  "Maritime Waterfront Swimming Program Authorization Release for ages 5-14: Sign Off",
  "Maritime Waterfront Activities Program Authorization Release for ages 9-14: Text",
  "Maritime Waterfront Activities Program Authorization Release for ages 9-14: Sign Off",
  "Media Authorization Release: Text",
  "Media Authorization Release: Sign Off",
  "Dismissal Consent Form: Text",
  "Dismissal Consent Form: Sign Off",
  "Dismissal Consent Form Afterschool Programs: Text",
  "Dismissal Consent Form Afterschool Programs: Sign Off",
  "Authorized to pick up child",
  "Describe Support Services",
  "Educational Setting",
  "How did you hear about us?",
  "IEP",
  "Insurance Phone Number",
  "Support Services",
  "T-Shirt Size",
  "Amount Paid",
  "Balance",
  "Refunded",
  "Balance Paid",
  "Total",
  "Payment Method",
] as const;

export type SimpleStateUpdater<S> = (prevState: S) => S;
